### ISSUE TITLE
Separação das informações em duas tabelas

### ISSUE THREAD

**Issue by fulviocanducci** [andrebaltieri/ibge#2]
Seria melhor gerar duas tabelas e separar as informações de unidade federativa da nação e outra para cidades?

**Comment by andrebaltieri** [comment]
Show, vi seu PR! É legal ter isto como opção... vamos deixar padronizado a tabela IBGE e nos scripts podemos ter uma pasta CUSTOM por exemplo com a separação em 2 tabelas... quem quiser usar, terá duas formas!

**Comment by fulviocanducci** [comment]
> Show, vi seu PR! É legal ter isto como opção... vamos deixar padronizado a tabela IBGE e nos scripts podemos ter uma pasta CUSTOM por exemplo com a separação em 2 tabelas... quem quiser usar, terá duas formas!

Foi adicionado conforme padrão inicial + pasta `Custom` com outro tipo de estrutura e tipo de dados assim fica conforme descrito por ti.
