### ISSUE TITLE
Sigla Estados

### ISSUE THREAD

**Issue by JoaoNascSilva** [andrebaltieri/ibge#7]
Boa Noite @andrebaltieri , 
Os estados de Roraima e Rondônia, estão com a mesma sigla 'RO', no arquivo Excel.

- Correto => Roraima [ RR ] e Rondônia [ RO ] .

**Comment by andrebaltieri** [comment]
- [x] Excel
- [x] SqlServer - Data
- [x] SqlServer - Update
- [x] MongoDb - Data
- [x] MongoDb - Update
- [x] MySql - Data
- [x] MySql - Update
- [x] Oracle - Data
- [x] Oracle - Update
- [x] PostgreSQL - Data
- [x] PostgreSQL - Update
- [x] FirebirdSQL - Data
- [x] FirebirdSQL - Update
- [x] SQLite - Data
- [x] SQLite - Update

@JoaoNascSilva muito obrigado pelo issue e pelo commit, eu fiz as correções no Excel que vai afetar os bancos futuros.
Infelizmente para os bancos atuais, precisamos de um patch de atualização.

#### Minha sugestão (O que fiz com o SQL Server)
Alterei o arquivo `Data.sql` na raiz da pasta, já refletindo a sigla de Rorâima como RR e criei uma pasta chamada DataFixes também na raiz, com o arquivo `2021-03-14-06-31_corrige_sigla_estado_roraima.sql` que fará UPDATE caso usuários não queiram recriar todos os itens.

Em resumo a ideia é:
- Alterar o `Data.sql` do banco, refletindo o Excel
- Criar um arquivo DataFix para update dos dados.

@fulviocanducci @yants95 @brunoemferreira

**Comment by brunoemferreira** [comment]
Assim como sugerido pelo @andrebaltieri foi feita a correção para o Banco Oracle, corrigindo o arquivo de Dados e gerando um patch para o estado de Roraima

**Comment by fulviocanducci** [comment]
Como sugerido pelo @andrebaltieri feitas as correções do MongoDB e MySQL.

**Comment by andrebaltieri** [comment]
Muito obrigado pessoal, e desculpem a falha <3

**Comment by marcopoloviana** [comment]
@andrebaltieri marquei o PostgreSQL como ok, e incluí o FirebirdSQL na lista. Caso eu tenha feito algo errado, só me falar rsrsrs abs

**Comment by andrebaltieri** [comment]
Muito obrigado pessoal <3
